### ISSUE TITLE
cannot execute dsflow -> no module named poyo

### ISSUE THREAD

**Issue by georgesryssen** [dsflow-io/dsflow#1]
![capture d ecran 2017-11-29 a 18 30 48](https://user-images.githubusercontent.com/28535379/33389628-d475b2e8-d533-11e7-9ec9-59848fc3f686.png)

**Comment by pmleveque** [comment]
can you do

`git pull`

then `cat init.sh`

**Comment by georgesryssen** [comment]
`git pull` executed
`cat init.sh` executed
`pip install poyo` executed

**Comment by pmleveque** [comment]
what do you see with `cat init.sh`?

**Comment by georgesryssen** [comment]
![capture d ecran 2017-11-29 a 18 38 46](https://user-images.githubusercontent.com/28535379/33389902-931e45f2-d534-11e7-93c1-a798005ac82c.png)

**Comment by georgesryssen** [comment]
![capture d ecran 2017-11-29 a 18 39 40](https://user-images.githubusercontent.com/28535379/33389949-b7c80514-d534-11e7-8f55-91fde53276bb.png)

**Comment by pmleveque** [comment]
hum, it looks like you installed pip or python with sudo, and now it requires the root user whenever you try to install something...

You could try `sudo pip install poyo`

**Comment by georgesryssen** [comment]
![capture d ecran 2017-11-29 a 18 41 06](https://user-images.githubusercontent.com/28535379/33389996-e3b917bc-d534-11e7-9ff9-fe1d400717e6.png)

**Comment by georgesryssen** [comment]
thanks, it works !
![capture d ecran 2017-11-29 a 18 42 25](https://user-images.githubusercontent.com/28535379/33390060-153e4442-d535-11e7-94ca-808ce31c0ef3.png)

**Comment by pmleveque** [comment]
did you install and launch Docker ?

(on Mac, double click on Docker in the Applications/ folder)

![image](https://user-images.githubusercontent.com/10697392/33390032-041139f4-d535-11e7-8cdc-d96f637041f8.png)

**Comment by pmleveque** [comment]
great!!

**Comment by georgesryssen** [comment]
i like the dsflow picture 👍
