### ISSUE TITLE
cannot execute `dsflow generate-job` -> No module named 'dsflow_core.models'

### ISSUE THREAD

**Issue by georgesryssen** [dsflow-io/dsflow#2]
![capture d ecran 2017-11-29 a 18 53 52](https://user-images.githubusercontent.com/28535379/33390588-ac015a76-d536-11e7-95e0-7424c53bb8ac.png)

**Comment by pmleveque** [comment]
I just fixed it. Sorry for that, I cleaned some code and didn't test it properly.
